# vim:ft=ansible:

# Author : Ashish Gaurav
# Email  : ashish@archsaber.com
#
---

- name: Ensure archsaber src directory
  become: yes
  file:
    path: /usr/local/src/archsaber/
    state: directory
    mode: 0755


- name: Get the latest installer script
  become: yes
  get_url:
    dest: /usr/local/src/archsaber/
    url: https://bin.archsaber.com/install/archagentctl
    mode: 0744

- name: Uninstall existing archagent
  command: /usr/local/src/archsaber/archagentctl -u
  when: archsaber_agent_force_reinstall  == true



- name: check for ArchAgent installation
  stat: path="/etc/opt/archsaber/license.json"
  register: result_archagent_installation


- name: run the script
  become: yes
  command: /usr/local/src/archsaber/archagentctl -i "{{archsaber_license}}"
  when: result_archagent_installation.stat.exists == false

- name: sync the data config
  template:
    src: "{{archagent_data_conf_template}}"
    dest: /etc/opt/archsaber/data.json
    mode: 0644
  when: archagent_sync_data_config
  notify:
    - restart archagent

- name: sync the aws metric config
  template:
    src: "{{archagent_aws_conf_template}}"
    dest: /etc/opt/archsaber/aws.json
    mode: 0644
  when: archagent_sync_data_config
  notify:
    - restart archagent

- name: sync the metric config
  template:
    src: "{{archagent_metric_conf_template}}"
    dest: /etc/opt/archsaber/metrics.json
    mode: 0644
  when: archagent_sync_metric_config
  notify:
    - restart archagent


- name: Ensure archagent is running
  become: yes
  service:
    name: archagent
    state: started
